Support emphasize-lines as an alias for hl_lines
rst2pdf/rst2pdf pull request #1246
Opened 2024-11-29 15:00 UTC by lornajane

Fixes #1057 to add support for `emphasize-lines` (note the hyphen!) for code blocks because Sphinx does. We usually use `hl_lines` because that's how it's named in Pygments.

With this change, both versions are supported, so that using `emphasize-lines` will render with either tool.

NOTE: if syntax highlighting is broken, or the dimming doesn't work, the tests don't fail. I think the colour changes aren't severe enough. I did add a test but I'm not confident it would catch a regression on this option name. Suggestions welcome!

2024-11-30 09:07 UTC, akrabat commented
Are we renaming to `emphasize-lines` and making `hl_lines` an alias? Logically we should as the Sphinx option is probably the most well-known in rst circles.

2024-12-01 11:36 UTC, lornajane commented
As I wrote it here, we're keeping `hl_lines` and supporting `emphasize-lines` as an alias. My logic is that we are wrapping/exposing Pygments features, which is our dependency. If Sphinx calls it something else then we can definitely be kind and support it, but it doesn't seem to be a docutils standard so I decided Pygments has the authority here, and that's also in line with what our existing users already expect. Definitely open to debate since I built it the other way around initially!

2024-12-01 15:06 UTC, akrabat requested changes

2024-12-01 15:06 UTC, akrabat commented on rst2pdf/directives/code_block.py
> +    # option hl_lines renamed to emphasize-lines for Sphinx compatibility
Let's go with `emphasize-lines` as the alias and reflect that in this comment.

2024-12-14 13:24 UTC, akrabat approved these changes
LGTM

2024-12-14 13:25 UTC, merged