fix versionadded & version changed directives
rst2pdf/rst2pdf pull request #982
Opened 2021-01-10 03:27 UTC by 2bndy5

closes #981 
I don't know when, but there was a change to how the `versionlabels` dict was declared (& possibly changed usage also) in Sphinx. This resulted in a failure to build a pdf when using `versionadded`, `versionchanged`, and `deprecated` directives.

See #981 for problematic output and concluding solution.

This PR fixes the pdfbuilder.py to compensate for the changes in Sphinx.

2021-01-10 10:59 UTC, lornajane requested changes
Thanks! It is so good to get this input from Sphinx users, as maintainers we mostly use rst2pdf directly. A couple of points before I'm ready to merge:

Could we get a test for this please so that we might spot if we regress it?

How does this change affect documents produced directly with rst2pdf, are these directives used in the rst2pdf output or just passed back to Sphinx? If so, please add a test showing that usage also.

2021-01-10 11:19 UTC, 2bndy5 commented
I mostly deal with libraries that require actual hardware to perform tests, so I'm afraid I'm rather inexperienced with creating pytests.

>How does this change affect documents produced directly with rst2pdf, are these directives used in the rst2pdf output or just passed back to Sphinx?

This is a good question. I had assumed that pdfbuilder.py was specific to using sphinx (because of the sphinx-like term "builder"). More reason to perform tests (or in my case learn to use them).

2021-01-10 23:07 UTC, 2bndy5 commented
do you have a recommendation of how/where to get the test's reference comparison output pdf?

>`reference` holds the "correct" version of the PDF for this test. When adding a test, put the desired PDF output into this file as well as supplying the tests in the `input` folder.

As a pytest noob, I find this a little confusing. If I just use the first "passing" output from running the test, then it feels counterproductive to do a comparison when the test doesn't `ERROR` out.

Also, I had no idea this lib was pinned to Sphinx v1.8.5. I'm afraid that might complicate the dependencies part of the proposed test. I found [the commit that introduced the breaking change](https://github.com/sphinx-doc/sphinx/commit/50ffe5b7c2e58b80ac379d8a1d300d12e5bf471f) solved by this PR. That commit predates Sphinx v1.8.5 (specifically released in v1.7.2)

2021-01-11 01:14 UTC, nfraprado commented
The idea is to create a simple document inside `tests/input` that relies on the change you did in this PR to work correctly. Then, after you run `pytest`, the output pdf for that document will be placed in `tests/output`. You should then copy that pdf to `tests/reference`, so that future `pytest` runs compare the generated pdf for your test with the reference pdf you just added.

So, the output pdf should differ from the reference one before your PR (making the test fail), but match it after the PR (making the test pass). Since, before your PR, this use case crashed rst2pdf it will generate an empty pdf causing the test to fail, which is fine, the procedure is the same :).

2021-01-11 01:21 UTC, nfraprado commented
Regarding Sphinx, if the breaking change was prior to version 1.8.5, then we should be fine testing your PR with this version.

2021-01-11 02:34 UTC, 2bndy5 commented
One last question before I have a go at making the test. Am I wrong in thinking that the `versionadded`, `versionchanged`, and `deprecated` directives are sphinx specific? Are these directives also defined by the rst specs?

I don't see them in [the docutil's reStructuredText Markup Specification for directives](https://docutils.sourceforge.io/docs/ref/rst/directives.html). Nor do I see a link for base case specifications of rst to adhere in the Contributing Guidelines.

2021-01-11 03:03 UTC, nfraprado commented
No, you're right, they're Sphinx-only: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html
And from what I can tell, `pdfbuilder.py` is indeed only used in Sphinx builds, so you should be fine with a single test using Sphinx.

Feel free to reach out if you have any issue with creating the test.

2021-01-11 09:28 UTC, 2bndy5 commented
The number one reason I like to contribute to others' libraries is for learning opportunities; this PR is no exception 😊 .

With that said, the new "sphinx-versionmodified" test passed on all 3 targeted versions of python. I chose the "sphinx-versionmodified" title for the test so its not as ambiguous as "sphinx-issue981".

I noticed that in the Contributing guidelines, [the instructions say to use a venv named `env`](https://github.com/rst2pdf/rst2pdf/blob/master/CONTRIBUTING.rst#set-up-to-run-tests), but the [gitignore file only ignores `.venv`](https://github.com/rst2pdf/rst2pdf/blob/f1d5efe17db0ee15ade0ed54c1f4520e4b7992ec/.gitignore#L12). If I were a total python/github noob, then I would have likely commit a venv titled `env` according to instruction. 👎🏻 

Also, I looked at the pre-commit-config.yml and followed [the link to an issue](https://github.com/psf/black/issues/438) in the comment about using a workaround. It would seem that issue was addressed in May 2020 and released in August 2020. This might serve as a separate issue, and I'm not sure if the workaround is needed anymore (I'm also new to pre-commit).

2021-01-11 10:09 UTC, akrabat commented
Be aware that we use `pytest` as a test runner. The actual tests are more like integration tests where we create an PDF file and compare it to a "known good" one in reference.

2021-01-11 10:15 UTC, 2bndy5 commented
>compare it to a "known good" one in reference.

The pdf I added to "tests/reference" does contain the expected output (using pytest on my fork's master branch of rst2pdf which should be based on upstream/master), but I understand there's more to a pdf than just the displayed contents. Does this mean I did something wrong?

2021-01-11 10:21 UTC, akrabat commented
> The pdf I added to "tests/reference" does contain the expected output (using pytest on my fork's master branch of rst2pdf which should be based on upstream/master), but I understand there's more to a pdf than just the displayed contents. Does this mean I did something wrong?

Nope. That's correct. The PDF in `tests/reference` is intended to be manually confirmed to be true by a human. When the tests are run, a new PDF is generated and the internal "objects" in it are compared with the reference PDF file.

2021-01-12 00:55 UTC, 2bndy5 commented
FYI tests still pass, but CI failed to upload artifacts from workflow. Normally I'd just re-run the workflow(s), but I don't see that option in the menus.

2021-01-12 01:01 UTC, nfraprado commented
Yeah, that happened to me recently as well. Whenever you push something the CI re-runs, so perhaps you could try force pushing again without changing anything? Though I'm not sure if a push with no change would really trigger the CI...

2021-01-13 21:48 UTC, lornajane approved these changes
This is in great shape, thanks so much for taking the time!

2021-01-13 21:52 UTC, lornajane commented
I'm confused about the state of the CI here and it's blocking me merging this right now. I'll come back to it when I can!

2021-01-13 22:25 UTC, 2bndy5 commented
Seems to me there is a difference between the current master branch's CI workflow and my fork's master branch's CI workflow. I think its related to the recent addition of building against python v3.9. 

I could rebase my fork's master branch to see if that helps, but that will likely require another PR approval as all current reviews would be disregarded.

2021-01-13 22:55 UTC, nfraprado commented
I think @lornajane meant that the PR wasn't mergeable 1 hour ago because the CI was waiting for approval first, before running the tests. It seems fine now, though.

2021-01-14 21:13 UTC, merged

2021-01-14 21:14 UTC, lornajane commented
Mmmmmm, not sure what was going on there, I had to reduce some of the protection settings on the branch to be able to merge it. Those strange CI jobs that don't exist and therefore don't pass were blocking it.